/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MultipleLinkedinAccountManagerRouteImport } from './routes/multiple-linkedin-account-manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinkedinPostSchedulerRouteImport } from './routes/linkedin-post-scheduler'
import { Route as LinkedinPostGeneratorRouteImport } from './routes/linkedin-post-generator'
import { Route as LinkedinContentCalendarRouteImport } from './routes/linkedin-content-calendar'
import { Route as LinkedinAiWriterRouteImport } from './routes/linkedin-ai-writer'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as AiLinkedinContentPlannerRouteImport } from './routes/ai-linkedin-content-planner'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCompleteRouteImport } from './routes/auth.complete'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRecruitingRouteImport } from './routes/app.recruiting'
import { Route as AppManagePostsRouteImport } from './routes/app.manage-posts'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCreateRouteImport } from './routes/app.create'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppAgentsRouteImport } from './routes/app.agents'
import { Route as AppAccountsRouteImport } from './routes/app.accounts'
import { Route as AppRecruitingNewRouteImport } from './routes/app.recruiting_.new'
import { Route as AppRecruitingJobIdRouteImport } from './routes/app.recruiting_.$jobId'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MultipleLinkedinAccountManagerRoute =
  MultipleLinkedinAccountManagerRouteImport.update({
    id: '/multiple-linkedin-account-manager',
    path: '/multiple-linkedin-account-manager',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinPostSchedulerRoute = LinkedinPostSchedulerRouteImport.update({
  id: '/linkedin-post-scheduler',
  path: '/linkedin-post-scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinPostGeneratorRoute = LinkedinPostGeneratorRouteImport.update({
  id: '/linkedin-post-generator',
  path: '/linkedin-post-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinContentCalendarRoute = LinkedinContentCalendarRouteImport.update({
  id: '/linkedin-content-calendar',
  path: '/linkedin-content-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinAiWriterRoute = LinkedinAiWriterRouteImport.update({
  id: '/linkedin-ai-writer',
  path: '/linkedin-ai-writer',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLinkedinContentPlannerRoute =
  AiLinkedinContentPlannerRouteImport.update({
    id: '/ai-linkedin-content-planner',
    path: '/ai-linkedin-content-planner',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteRoute = AuthCompleteRouteImport.update({
  id: '/auth/complete',
  path: '/auth/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruitingRoute = AppRecruitingRouteImport.update({
  id: '/recruiting',
  path: '/recruiting',
  getParentRoute: () => AppRoute,
} as any)
const AppManagePostsRoute = AppManagePostsRouteImport.update({
  id: '/manage-posts',
  path: '/manage-posts',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruitingNewRoute = AppRecruitingNewRouteImport.update({
  id: '/recruiting_/new',
  path: '/recruiting/new',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruitingJobIdRoute = AppRecruitingJobIdRouteImport.update({
  id: '/recruiting_/$jobId',
  path: '/recruiting/$jobId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-linkedin-content-planner': typeof AiLinkedinContentPlannerRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/linkedin-ai-writer': typeof LinkedinAiWriterRoute
  '/linkedin-content-calendar': typeof LinkedinContentCalendarRoute
  '/linkedin-post-generator': typeof LinkedinPostGeneratorRoute
  '/linkedin-post-scheduler': typeof LinkedinPostSchedulerRoute
  '/login': typeof LoginRoute
  '/multiple-linkedin-account-manager': typeof MultipleLinkedinAccountManagerRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/create': typeof AppCreateRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/library': typeof AppLibraryRoute
  '/app/manage-posts': typeof AppManagePostsRoute
  '/app/recruiting': typeof AppRecruitingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/app/recruiting/$jobId': typeof AppRecruitingJobIdRoute
  '/app/recruiting/new': typeof AppRecruitingNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-linkedin-content-planner': typeof AiLinkedinContentPlannerRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/linkedin-ai-writer': typeof LinkedinAiWriterRoute
  '/linkedin-content-calendar': typeof LinkedinContentCalendarRoute
  '/linkedin-post-generator': typeof LinkedinPostGeneratorRoute
  '/linkedin-post-scheduler': typeof LinkedinPostSchedulerRoute
  '/login': typeof LoginRoute
  '/multiple-linkedin-account-manager': typeof MultipleLinkedinAccountManagerRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/create': typeof AppCreateRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/library': typeof AppLibraryRoute
  '/app/manage-posts': typeof AppManagePostsRoute
  '/app/recruiting': typeof AppRecruitingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/app/recruiting/$jobId': typeof AppRecruitingJobIdRoute
  '/app/recruiting/new': typeof AppRecruitingNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-linkedin-content-planner': typeof AiLinkedinContentPlannerRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/linkedin-ai-writer': typeof LinkedinAiWriterRoute
  '/linkedin-content-calendar': typeof LinkedinContentCalendarRoute
  '/linkedin-post-generator': typeof LinkedinPostGeneratorRoute
  '/linkedin-post-scheduler': typeof LinkedinPostSchedulerRoute
  '/login': typeof LoginRoute
  '/multiple-linkedin-account-manager': typeof MultipleLinkedinAccountManagerRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/create': typeof AppCreateRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/library': typeof AppLibraryRoute
  '/app/manage-posts': typeof AppManagePostsRoute
  '/app/recruiting': typeof AppRecruitingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/app/recruiting_/$jobId': typeof AppRecruitingJobIdRoute
  '/app/recruiting_/new': typeof AppRecruitingNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-linkedin-content-planner'
    | '/app'
    | '/forgot-password'
    | '/help'
    | '/linkedin-ai-writer'
    | '/linkedin-content-calendar'
    | '/linkedin-post-generator'
    | '/linkedin-post-scheduler'
    | '/login'
    | '/multiple-linkedin-account-manager'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/privacy-policy'
    | '/signup'
    | '/terms'
    | '/terms-of-service'
    | '/app/accounts'
    | '/app/agents'
    | '/app/calendar'
    | '/app/create'
    | '/app/dashboard'
    | '/app/library'
    | '/app/manage-posts'
    | '/app/recruiting'
    | '/app/settings'
    | '/app/support'
    | '/auth/complete'
    | '/app/recruiting/$jobId'
    | '/app/recruiting/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-linkedin-content-planner'
    | '/app'
    | '/forgot-password'
    | '/help'
    | '/linkedin-ai-writer'
    | '/linkedin-content-calendar'
    | '/linkedin-post-generator'
    | '/linkedin-post-scheduler'
    | '/login'
    | '/multiple-linkedin-account-manager'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/privacy-policy'
    | '/signup'
    | '/terms'
    | '/terms-of-service'
    | '/app/accounts'
    | '/app/agents'
    | '/app/calendar'
    | '/app/create'
    | '/app/dashboard'
    | '/app/library'
    | '/app/manage-posts'
    | '/app/recruiting'
    | '/app/settings'
    | '/app/support'
    | '/auth/complete'
    | '/app/recruiting/$jobId'
    | '/app/recruiting/new'
  id:
    | '__root__'
    | '/'
    | '/ai-linkedin-content-planner'
    | '/app'
    | '/forgot-password'
    | '/help'
    | '/linkedin-ai-writer'
    | '/linkedin-content-calendar'
    | '/linkedin-post-generator'
    | '/linkedin-post-scheduler'
    | '/login'
    | '/multiple-linkedin-account-manager'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/privacy-policy'
    | '/signup'
    | '/terms'
    | '/terms-of-service'
    | '/app/accounts'
    | '/app/agents'
    | '/app/calendar'
    | '/app/create'
    | '/app/dashboard'
    | '/app/library'
    | '/app/manage-posts'
    | '/app/recruiting'
    | '/app/settings'
    | '/app/support'
    | '/auth/complete'
    | '/app/recruiting_/$jobId'
    | '/app/recruiting_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiLinkedinContentPlannerRoute: typeof AiLinkedinContentPlannerRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LinkedinAiWriterRoute: typeof LinkedinAiWriterRoute
  LinkedinContentCalendarRoute: typeof LinkedinContentCalendarRoute
  LinkedinPostGeneratorRoute: typeof LinkedinPostGeneratorRoute
  LinkedinPostSchedulerRoute: typeof LinkedinPostSchedulerRoute
  LoginRoute: typeof LoginRoute
  MultipleLinkedinAccountManagerRoute: typeof MultipleLinkedinAccountManagerRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  AuthCompleteRoute: typeof AuthCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiple-linkedin-account-manager': {
      id: '/multiple-linkedin-account-manager'
      path: '/multiple-linkedin-account-manager'
      fullPath: '/multiple-linkedin-account-manager'
      preLoaderRoute: typeof MultipleLinkedinAccountManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin-post-scheduler': {
      id: '/linkedin-post-scheduler'
      path: '/linkedin-post-scheduler'
      fullPath: '/linkedin-post-scheduler'
      preLoaderRoute: typeof LinkedinPostSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin-post-generator': {
      id: '/linkedin-post-generator'
      path: '/linkedin-post-generator'
      fullPath: '/linkedin-post-generator'
      preLoaderRoute: typeof LinkedinPostGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin-content-calendar': {
      id: '/linkedin-content-calendar'
      path: '/linkedin-content-calendar'
      fullPath: '/linkedin-content-calendar'
      preLoaderRoute: typeof LinkedinContentCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin-ai-writer': {
      id: '/linkedin-ai-writer'
      path: '/linkedin-ai-writer'
      fullPath: '/linkedin-ai-writer'
      preLoaderRoute: typeof LinkedinAiWriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-linkedin-content-planner': {
      id: '/ai-linkedin-content-planner'
      path: '/ai-linkedin-content-planner'
      fullPath: '/ai-linkedin-content-planner'
      preLoaderRoute: typeof AiLinkedinContentPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete': {
      id: '/auth/complete'
      path: '/auth/complete'
      fullPath: '/auth/complete'
      preLoaderRoute: typeof AuthCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recruiting': {
      id: '/app/recruiting'
      path: '/recruiting'
      fullPath: '/app/recruiting'
      preLoaderRoute: typeof AppRecruitingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manage-posts': {
      id: '/app/manage-posts'
      path: '/manage-posts'
      fullPath: '/app/manage-posts'
      preLoaderRoute: typeof AppManagePostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/create': {
      id: '/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/accounts': {
      id: '/app/accounts'
      path: '/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recruiting_/new': {
      id: '/app/recruiting_/new'
      path: '/recruiting/new'
      fullPath: '/app/recruiting/new'
      preLoaderRoute: typeof AppRecruitingNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recruiting_/$jobId': {
      id: '/app/recruiting_/$jobId'
      path: '/recruiting/$jobId'
      fullPath: '/app/recruiting/$jobId'
      preLoaderRoute: typeof AppRecruitingJobIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppAgentsRoute: typeof AppAgentsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCreateRoute: typeof AppCreateRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppManagePostsRoute: typeof AppManagePostsRoute
  AppRecruitingRoute: typeof AppRecruitingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppRecruitingJobIdRoute: typeof AppRecruitingJobIdRoute
  AppRecruitingNewRoute: typeof AppRecruitingNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppAgentsRoute: AppAgentsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCreateRoute: AppCreateRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppManagePostsRoute: AppManagePostsRoute,
  AppRecruitingRoute: AppRecruitingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSupportRoute: AppSupportRoute,
  AppRecruitingJobIdRoute: AppRecruitingJobIdRoute,
  AppRecruitingNewRoute: AppRecruitingNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiLinkedinContentPlannerRoute: AiLinkedinContentPlannerRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LinkedinAiWriterRoute: LinkedinAiWriterRoute,
  LinkedinContentCalendarRoute: LinkedinContentCalendarRoute,
  LinkedinPostGeneratorRoute: LinkedinPostGeneratorRoute,
  LinkedinPostSchedulerRoute: LinkedinPostSchedulerRoute,
  LoginRoute: LoginRoute,
  MultipleLinkedinAccountManagerRoute: MultipleLinkedinAccountManagerRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  AuthCompleteRoute: AuthCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
